baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[security.exec]
    allow = ['^asciidoctor$']

[markup]
  [markup.asciidocExt]
    workingFolderCurrent = true
    [markup.asciidocExt.attributes]
      source-highlighter = 'rouge'

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
